const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },{
        src: './images/kurly_003.jpg',
        name: '[풀무원] 여름철 시원한 냉모밀',
        summary: '깔끔하고 시원한 한끼',
        price: 4980,
        sale: 10,
        review: 87,
    },
    {
        src: './images/kurly_004.jpg',
        name: '[빙그레] 바나나맛 아이스크림 6개입',
        summary: '달콤한 바나나맛의 시원함',
        price: 5200,
        sale: 15,
        review: 102,
    },
    {
        src: './images/kurly_005.jpg',
        name: '[청정원] 쿨~한 열무 비빔국수',
        summary: '여름 별미로 제격!',
        price: 5900,
        sale: 12,
        review: 65,
    },
    {
        src: './images/kurly_006.jpg',
        name: '[오뚜기] 컵누들 냉칼국수',
        summary: '가볍고 시원한 다이어트 한끼',
        price: 1450,
        sale: 5,
        review: 134,
    },
    {
        src: './images/kurly_007.jpg',
        name: '[팔도] 비빔면 오리지널 5개입',
        summary: '한국인의 여름 라면',
        price: 3850,
        sale: 10,
        review: 215,
    },
    {
        src: './images/kurly_008.jpg',
        name: '[롯데] 아이스홍시 10개입',
        summary: '자연의 달콤함 그대로',
        price: 9800,
        sale: 8,
        review: 72,
    },
    {
        src: './images/kurly_009.jpg',
        name: '[삼양] 불닭비빔면 화끈하게 매운맛',
        summary: '매운 걸 좋아한다면 추천!',
        price: 4320,
        sale: 13,
        review: 98,
    },
    {
        src: './images/kurly_010.jpg',
        name: '[매일유업] 흰 우유 아이스바',
        summary: '우유 본연의 시원한 맛',
        price: 6200,
        sale: 18,
        review: 47,
    },
    {
        src: './images/kurly_011.jpg',
        name: '[CJ] 햇반 컵반 냉콩국수',
        summary: '간편하고 시원한 한끼',
        price: 4500,
        sale: 7,
        review: 55,
    },
    {
        src: './images/kurly_012.jpg',
        name: '[빙그레] 메로나 수박맛',
        summary: '달콤한 수박맛의 여름 간식',
        price: 3600,
        sale: 20,
        review: 190,
    }
]